#!/usr/bin/env bash

[[ -z "$1" ]] && echo "Usage: $0 <input.md>" && exit 1

CSS_FILES=$(find styles/ -name "*.css" -exec echo --css={} \;)
python process.py $1 | pandoc -f gfm --mathjax $CSS_FILES --template=template.html --standalone -t html -o out.html
